export const APP_CONTEXT_TYPES = {
  DISPLAY_ALERT: 'SHOW_ALERT',
  CLEAR_ALERT: 'CLEAR_ALERT',
};

export const REGISTER_CONTEXT_TYPES = {
  REGISTER_USER_BEGIN: 'REGISTER_USER_BEGIN',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',
};

export const LOGIN_CONTEXT_TYPES = {
  LOGIN_USER_BEGIN: 'LOGIN_USER_BEGIN',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
};

export const NAVBAR_CONTEXT_TYPES = {
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
};

export const USER_CONTEXT_TYPES = {
  LOGOUT_USER: 'LOGOUT_USER',
};

export const UPDATE_CONTEXT_TYPES = {
  UPDATE_USER_BEGIN: 'UPDATE_USER_BEGIN',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',
};

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

export const CREATE_JOB_CONTEXT = {
  CREATE_JOB_BEGIN: 'CREATE_JOB_BEGIN',
  CREATE_JOB_SUCCESS: 'CREATE_JOB_SUCCESS',
  CREATE_JOB_ERROR: 'CREATE_JOB_ERROR',
};

export const GET_JOB_CONTEXT = {
  GET_JOB_BEGIN: 'GET_JOB_BEGIN',
  GET_JOB_SUCCESS: 'GET_JOB_SUCCESS',
};

export const SET_EDIT_JOB = 'SET_EDIT_JOB';
export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN';
export const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR';

export const EDIT_JOB_CONTEXT = {
  EDIT_JOB_BEGIN: 'EDIT_JOB_BEGIN',
  EDIT_JOB_SUCCESS: 'EDIT_JOB_SUCCESS',
  EDIT_JOB_ERROR: 'EDIT_JOB_ERROR',
};

export const SHOW_STATS_CONTEXT = {
  SHOW_STATS_BEGIN: 'SHOW_STATS_BEGIN',
  SHOW_STATS_SUCCESS: 'SHOW_STATS_SUCCESS',
};

export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const CHANGE_PAGE = 'CHANGE_PAGE';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
